"""
backend/tests/test_external_clients.py
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Unit tests for external AI provider API clients:
  - GeminiClient (Google Gemini API)
  - ZeroGPTClient (ZeroGPT AI Text API)
  - HuggingFaceClient (Hugging Face Inference API)
"""
from __future__ import annotations

import json
import pytest
from unittest.mock import AsyncMock, patch, MagicMock
import httpx

from app.services.gemini_client import GeminiClient
from app.services.zerogpt_client import ZeroGPTClient
from app.services.huggingface_client import HuggingFaceClient


# ─── GeminiClient Tests ────────────────────────────────────────────────────────

@pytest.mark.asyncio
async def test_gemini_unconfigured_fallback():
    client = GeminiClient(api_key="")
    assert not client.is_configured
    res = await client.analyze_multimodal_media(b"fake_image_bytes")
    assert res["available"] is False
    assert res["score"] == 0.0
    assert "unconfigured" in res["reasoning"].lower()


@pytest.mark.asyncio
async def test_gemini_multimodal_analysis_success():
    client = GeminiClient(api_key="test-gemini-key")
    mock_gemini_response = {
        "candidates": [
            {
                "content": {
                    "parts": [
                        {
                            "text": json.dumps({
                                "deepfake_score": 0.85,
                                "is_ai_generated": True,
                                "confidence": 92.0,
                                "reasoning": "Facial texture inconsistencies and synthetic lighting patterns detected.",
                                "flags": ["Facial Texture Anomaly", "Unnatural Reflection"]
                            })
                        }
                    ]
                }
            }
        ]
    }

    mock_resp = MagicMock()
    mock_resp.status_code = 200
    mock_resp.json.return_value = mock_gemini_response

    with patch("httpx.AsyncClient.post", new_callable=AsyncMock) as mock_post:
        mock_post.return_value = mock_resp
        res = await client.analyze_multimodal_media(b"sample_image_data", mime_type="image/png")

        assert res["available"] is True
        assert res["score"] == 0.85
        assert res["confidence"] == 92.0
        assert res["is_ai_generated"] is True
        assert len(res["flags"]) == 2


@pytest.mark.asyncio
async def test_gemini_request_exception():
    client = GeminiClient(api_key="test-gemini-key")
    with patch("httpx.AsyncClient.post", side_effect=httpx.ConnectTimeout("Connection timeout")):
        res = await client.analyze_multimodal_media(b"data")
        assert res["available"] is False
        assert "exception" in res["reasoning"].lower()


# ─── ZeroGPTClient Tests ───────────────────────────────────────────────────────

@pytest.mark.asyncio
async def test_zerogpt_unconfigured_fallback():
    client = ZeroGPTClient(api_key="")
    assert not client.is_configured
    res = await client.detect_ai_text("Sample text content to test zero gpt fallback")
    assert res["available"] is False
    assert res["score"] == 0.0
    assert "unconfigured" in res["feedback"].lower()


@pytest.mark.asyncio
async def test_zerogpt_detection_success():
    client = ZeroGPTClient(api_key="test-zerogpt-key")
    mock_zerogpt_response = {
        "success": True,
        "data": {
            "fakePercentage": 88.5,
            "textWords": 45,
            "feedback": "Your text is most likely written by AI",
        }
    }

    mock_resp = MagicMock()
    mock_resp.status_code = 200
    mock_resp.json.return_value = mock_zerogpt_response

    with patch("httpx.AsyncClient.post", new_callable=AsyncMock) as mock_post:
        mock_post.return_value = mock_resp
        res = await client.detect_ai_text("This text was generated by an advanced large language model for testing.")

        assert res["available"] is True
        assert res["score"] == 0.885
        assert res["fake_percentage"] == 88.5
        assert res["is_human"] is False
        assert res["words_count"] == 45


# ─── HuggingFaceClient Tests ───────────────────────────────────────────────────

@pytest.mark.asyncio
async def test_huggingface_unconfigured_fallback():
    client = HuggingFaceClient(api_key="")
    assert not client.is_configured
    res = await client.classify_image_deepfake(b"binary_image_data")
    assert res["available"] is False
    assert res["score"] == 0.0
    assert "unconfigured" in res["reasoning"].lower()


@pytest.mark.asyncio
async def test_huggingface_classification_success():
    client = HuggingFaceClient(api_key="test-hf-key")
    mock_hf_predictions = [
        {"label": "Fake", "score": 0.94},
        {"label": "Real", "score": 0.06},
    ]

    mock_resp = MagicMock()
    mock_resp.status_code = 200
    mock_resp.json.return_value = mock_hf_predictions

    with patch("httpx.AsyncClient.post", new_callable=AsyncMock) as mock_post:
        mock_post.return_value = mock_resp
        res = await client.classify_image_deepfake(b"image_bytes")

        assert res["available"] is True
        assert res["score"] == 0.94
        assert res["confidence"] == 94.0
        assert res["top_label"] == "Fake"
