"""
app/services/explainer_service.py
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Plain-Language Summary & Explainable AI (XAI) Generator

Translates technical neural network scores, FFT spectral artifacts,
rPPG pulse irregularities, and URL indicators into clear, non-technical
summaries for end users.
"""
from typing import Dict, List, Any


def generate_simple_summary(
    media_type: str,
    verdict: str,
    confidence: float,
    flags: List[Any],
    engine_metadata: Dict[str, Any]
) -> Dict[str, Any]:
    """
    Generate a plain-language Explainable AI (XAI) summary.

    Returns:
        Dict with verdict_label, confidence_percentage, trust_level,
        headline, key_findings, why_this_result, action_recommendation
    """
    # Normalize confidence
    conf_pct = round(confidence, 1)

    # 1. Trust Level & Verdict Label
    if verdict == "AUTHENTIC" or conf_pct < 35.0:
        trust_level = "GREEN"
        verdict_label = "Authentic & Genuine"
    elif verdict == "SUSPICIOUS" or (35.0 <= conf_pct < 65.0):
        trust_level = "AMBER"
        verdict_label = "Suspicious / Needs Review"
    else:
        trust_level = "RED"
        if media_type == "url":
            verdict_label = "Likely Phishing / Malicious Site"
        else:
            verdict_label = "Likely AI-Generated / Deepfake"

    # 2. Extract technical indicators from engine_metadata & flags
    fft_score = float(engine_metadata.get("fft_anomaly_score", 0.0))
    spatial_score = float(engine_metadata.get("spatial_score", conf_pct / 100.0 if media_type == "image" else 0.0))
    temporal_score = float(engine_metadata.get("temporal_score", 0.0))
    rppg_score = float(engine_metadata.get("rppg_anomaly_score", 0.0))
    audio_score = float(engine_metadata.get("audio_score", conf_pct / 100.0 if media_type == "audio" else 0.0))
    lip_sync_score = float(engine_metadata.get("lip_sync_score", 0.0))
    ai_text_score = float(engine_metadata.get("ai_text_score", 0.0))
    domain_age_days = engine_metadata.get("domain_age_days", None)
    is_typosquat = engine_metadata.get("is_typosquatting", False)

    flag_labels = [f.label if hasattr(f, 'label') else f.get('label', '') for f in flags]

    key_findings: List[str] = []

    # 3. Media-Specific Rules Implementation
    if media_type == "image":
        if fft_score > 0.6:
            key_findings.append("Frequency Noise: Hidden pixel noise patterns generated by AI image tools.")
        elif fft_score > 0.35:
            key_findings.append("Pixel Irregularities: Minor high-frequency noise detected in texture patterns.")

        if spatial_score > 0.7 or "GAN Fingerprint Detected" in flag_labels:
            key_findings.append("AI Texture Artifacts: Unnatural facial symmetry, distorted ears/eyes, or artificial skin smoothing.")
        elif spatial_score > 0.4:
            key_findings.append("Slight Distortion: Soft boundary lines detected around facial feature edges.")

        if "No Face Detected" in flag_labels:
            key_findings.append("Non-Facial Analysis: Evaluated purely on background textures and pixel grid frequencies.")
        else:
            key_findings.append("Facial Structure Check: Mapped key facial landmarks against real human biological baselines.")

    elif media_type == "video":
        if lip_sync_score > 0.5 or "Lip-Sync Discrepancy" in flag_labels:
            key_findings.append("Audio-Visual Discrepancy: The mouth movements do not perfectly match the spoken audio track.")
        
        if temporal_score > 0.6 or rppg_score > 0.5 or "rPPG Liveness Anomaly" in flag_labels:
            key_findings.append("Unnatural Blinking & Liveness: Flickering frame edges, missing eye blinks, or unnatural biological pulse patterns.")
        else:
            key_findings.append("Frame Continuity: Evaluated smooth transition consistency between individual video frames.")

        if spatial_score > 0.5:
            key_findings.append("Frame Blending Artifacts: AI face-swap boundaries detected across multiple keyframes.")

    elif media_type == "audio":
        if audio_score > 0.65 or "Voice Clone Signature" in flag_labels:
            key_findings.append("Synthetic Voice Pitch: Artificial vocal cadence with missing natural human breath pauses.")
        elif audio_score > 0.35:
            key_findings.append("Acoustic Spectrum Variance: Subtle robotic audio frequencies found in speech pitch.")
        
        key_findings.append("Spectrogram Analysis: Evaluated voice energy distribution across high and low sound frequencies.")

    elif media_type == "pdf" or media_type == "document":
        if ai_text_score > 0.7 or "AI Generated Phrasing" in flag_labels:
            key_findings.append("AI Text Patterns: Text phrasing matches language patterns typical of AI writing assistants (ChatGPT/Claude).")
        
        if "Modified Metadata" in flag_labels or "EXIF Metadata Anomaly" in flag_labels:
            key_findings.append("Modified File History: File metadata indicates recent editing with digital document manipulation tools.")

        key_findings.append("Document Structure: Analyzed hidden PDF streams, font embeds, and metadata timestamps.")

    elif media_type == "url":
        if (domain_age_days is not None and domain_age_days < 30) or "Recent Domain Creation" in flag_labels:
            key_findings.append("Recently Registered Domain: This website was registered very recently, which is common for short-lived phishing sites.")
        
        if is_typosquat or "Typosquatting Detected" in flag_labels:
            key_findings.append("Lookalike Domain: This URL looks similar to a well-known brand name but contains subtle spelling variations.")

        if "IP Address Host" in flag_labels:
            key_findings.append("Raw IP Hostname: The link connects directly to a raw server IP rather than a registered web domain name.")

    # Fallback findings if list is empty
    if not key_findings:
        if trust_level == "GREEN":
            key_findings = [
                "Natural Pixel Distribution: Texture, lighting, and noise align with authentic digital captures.",
                "Biological Alignment: Facial structure and proportions fall within normal biological ranges.",
                "Clean Provenance: No evidence of artificial generation or deceptive manipulation."
            ]
        else:
            key_findings = [
                "Statistical Anomaly: Neural network confidence indicates non-standard generation signatures.",
                "Texture Distortion: Subtle boundary artifacts observed in critical feature regions.",
                "Forensic Inconsistency: Multiple minor indicators combine to reduce overall authenticity confidence."
            ]

    # Limit to top 4 findings max
    key_findings = key_findings[:4]

    # 4. Generate Headline & Why This Result & Action Recommendation
    if trust_level == "GREEN":
        headline = f"This {media_type} appears to be authentic and shows no major AI manipulation markers."
        why_this_result = (
            f"Our AI engines analyzed the {media_type}'s structural patterns, frequency spectra, and metadata. "
            "All indicators fall within natural parameters expected of genuine human-created media."
        )
        action_recommendation = (
            "Safe to view and share. No immediate risk indicators or artificial deepfake markers were detected."
        )
    elif trust_level == "AMBER":
        headline = f"This {media_type} contains suspicious indicators and warrants careful manual review."
        why_this_result = (
            f"Our system detected minor anomalies in the {media_type}'s texture, metadata, or signal patterns. "
            "While not conclusively artificial, these signatures are uncharacteristic of typical authentic files."
        )
        action_recommendation = (
            "Exercise caution before relying on this media. Verify the source independently or inspect advanced technical details."
        )
    else: # RED
        if media_type == "url":
            headline = "High threat level: This web link shows strong indicators of a phishing website."
            why_this_result = (
                "Our security scanner analyzed the domain registration, URL structure, and host reputation. "
                "It detected deceptive spelling patterns or server configurations frequently used in phishing attacks."
            )
            action_recommendation = (
                "Do not enter passwords, credit card numbers, or personal information on this site. Avoid clicking unverified links."
            )
        else:
            headline = f"This {media_type} shows strong visual and mathematical patterns typical of AI generators."
            why_this_result = (
                f"Our system analyzed the {media_type}'s lighting, symmetry, frequency noise, and structural coherence. "
                "It identified multiple artificial anomalies that rarely occur in natural camera or microphone recordings."
            )
            action_recommendation = (
                "Do not rely on this media for identity verification, legal evidence, or news reporting without secondary verification."
            )

    return {
        "verdict_label": verdict_label,
        "confidence_percentage": conf_pct,
        "trust_level": trust_level,
        "headline": headline,
        "key_findings": key_findings,
        "why_this_result": why_this_result,
        "action_recommendation": action_recommendation,
    }
